[package]
name = "pharia-skill-cli"
version = "0.1.17"
edition = "2021"
repository = "https://github.com/Aleph-Alpha/pharia-skill-cli"

[dependencies]
clap = { version = "4.5.21", features = ["env", "derive"] }
mime = "0.3.17"
oci-client = "0.14.0"
oci-wasm = "0.2.0"
reqwest = "0.12.8"
serde_json = "1.0.133"
tokio = { version = "1.41.1", features = [
    "macros",
    "rt-multi-thread",
    "signal",
] }

[dev-dependencies]
assert_cmd = "2.0.16"
dotenvy = "0.15.7"
predicates = "3.1.2"
wat = "1.221.0"
pharia-kernel = { registry = "jfrog", version = "0.3.1" }

# The profile that 'dist' will build with
[profile.dist]
inherits = "release"
lto = "thin"
