[package]
name = "pharia-skill-cli"
version = "0.3.1"
edition = "2021"
repository = "https://github.com/Aleph-Alpha/pharia-skill-cli"

[dependencies]
clap = { version = "4.5.29", features = ["env", "derive"] }
mime = "0.3.17"
oci-client = "0.14.0"
oci-wasm = "0.2.1"
reqwest = "0.12.12"
serde_json = "1.0.138"
tokio = { version = "1.43.0", features = [
    "macros",
    "rt-multi-thread",
    "signal",
] }

[dev-dependencies]
assert_cmd = "2.0.16"
dotenvy = "0.15.7"
predicates = "3.1.3"
wat = "1.225.0"
pharia-kernel = { registry = "jfrog", version = "0.9.3" }

# The profile that 'dist' will build with
[profile.dist]
inherits = "release"
lto = "thin"
