[package]
name = "pharia-skill"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.7", features = ["env", "derive"] }

[lints]
workspace = true

[dev-dependencies]
assert_cmd = "2.0.14"
