[package]
name = "pharia-skill-cli"
version = "0.1.16"
edition = "2021"
repository = "https://github.com/Aleph-Alpha/pharia-skill-cli"

[dependencies]
clap = { version = "4.5.20", features = ["env", "derive"] }
mime = "0.3.17"
oci-client = "0.13.0"
oci-wasm = "0.1.0"
reqwest = "0.12.8"
serde_json = "1.0.132"
tokio = { version = "1.41.0", features = [
    "macros",
    "rt-multi-thread",
    "signal",
] }

[dev-dependencies]
assert_cmd = "2.0.16"
dotenvy = "0.15.7"
predicates = "3.1.2"
wat = "1.219.1"
pharia-kernel = { registry = "jfrog", version = "0.1.0" }

# The profile that 'dist' will build with
[profile.dist]
inherits = "release"
lto = "thin"
