[package]
name = "pharia-skill"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.16", features = ["env", "derive"] }
mime = "0.3.17"
oci-client = "0.12.1"
oci-wasm = "0.0.5"
reqwest = "0.12.7"
serde_json = "1.0.125"
tokio = { version = "1.39.3", features = [
    "macros",
    "rt-multi-thread",
    "signal",
] }

[lints]
workspace = true

[dev-dependencies]
assert_cmd = "2.0.16"
dotenvy = "0.15.7"
predicates = "3.1.2"
wat = "1.216.0"
pharia-kernel = { path = ".." }
