[package]
name = "pharia-skill"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.8", features = ["env", "derive"] }
oci-distribution = "0.11.0"
oci-wasm = "0.0.4"
tokio = { version = "1.38.0", features = [
    "macros",
    "rt-multi-thread",
    "signal",
] }

[lints]
workspace = true

[dev-dependencies]
assert_cmd = "2.0.14"
dotenvy = "0.15.7"
wat = "1.212.0"
