[package]
name = "pharia-skill"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.15", features = ["env", "derive"] }
mime = "0.3.17"
oci-distribution = "0.11.0"
oci-wasm = "0.0.4"
reqwest = "0.12.5"
serde_json = "1.0.124"
tokio = { version = "1.39.2", features = [
    "macros",
    "rt-multi-thread",
    "signal",
] }

[lints]
workspace = true

[dev-dependencies]
assert_cmd = "2.0.16"
dotenvy = "0.15.7"
predicates = "3.1.2"
wat = "1.214.0"
pharia-kernel = { path = ".." }
