name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  id-token: write
  packages: write

env:
  CARGO_TERM_COLOR: always
  SKILL_REGISTRY: ghcr.io
  SKILL_REPOSITORY: aleph-alpha/pharia-skill-cli/skills
  SKILL_REGISTRY_USER: ${{ github.actor }}
  SKILL_REGISTRY_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  PHARIA_AI_TOKEN: ${{ secrets.PHARIA_AI_TOKEN }}

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - name: Run cargo test
        run: cargo test --all-features

  lints:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy
      - uses: Swatinem/rust-cache@v2
      - run: cargo fmt -- --check
      - run: cargo clippy --all-features --all-targets
